[package]
name = "jolt-core"
version = "0.1.0"
authors = [
    # author of original Spartan paper and code base 
    "Srinath Setty <srinath@microsoft.com>",
    # authors who contributed to the Arkworks Spartan fork
    "Zhenfei Zhang <zhenfei.zhang@hotmail.com>",
    # authors who contributed to Lasso/Jolt
    "Michael Zhu <mzhu@a16z.com>",
    "Sam Ragsdale <sragsdale@a16z.com>",
    "Noah Citron <ncitron@a16z.com>",
    "Arasu Arun <arasu.arun5@gmail.com>",
    # authors who contributed to Jolty2
    "Zhenfei Zhang <zhenfei.zhang@hotmail.com>",
]

edition = "2021"
description = "The lookup singularity. Based on Spartan; built on Arkworks."
documentation = "https://github.com/a16z/jolt/README.md"
repository = "https://github.com/a16z/jolt"
license-file = "LICENSE"
keywords = ["SNARK", "cryptography", "proofs"]

[dependencies]
ark-std = "0.4.0"
clap = { version = "4.3.10", features = ["derive"] }
criterion = { version = "0.5.1", features = ["html_reports"] }
digest = "0.8.1"
enum_dispatch = "0.3.12"
ff = "0.13.0"
fixedbitset = "0.5.0"
goldilocks = { git = "https://github.com/zhenfeizhang/Goldilocks" }
halo2curves = "0.1.0"
itertools = "0.10.0"
lazy_static = "1.4.0"
merlin = "3.0.0"
num-integer = "0.1.45"
postcard = { version = "1.0.8", default-features = false, features = [
    "use-std",
] }
rand = "0.7.3"
rand_chacha = { version = "0.3.0", default-features = false }
rand_core = { version = "0.5", default-features = false }
rayon = { version = "^1.8.0", optional = true }
rgb = "0.8.37"
serde = { version = "1.0.*", default-features = false, features = ["derive"] }
sha3 = "0.8.2"
smallvec = "1.13.1"
strum = "0.25.0"
strum_macros = "0.25.2"
textplots = "0.8.4"
thiserror = "1.0.58"
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-flame = "0.2.0"
tracing-subscriber = "0.3.18"
tracing-texray = "0.2.0"
iai-callgrind = "0.10.2"

common = { path = "../common" }
tracer = { path = "../tracer" }
bincode = "1.3.3"

[build-dependencies]
common = { path = "../common" }

[[bench]]
name = "iai"
harness = false

[lib]
name = "jolt_core"
path = "src/lib.rs"

[features]
default = [
    "multicore",
]
multicore = ["rayon"]
